apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.claimName }}
  namespace: jenkins
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.storage }}
  storageClassName: {{ .Values.volume.class }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.app }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deployment.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.app }}
        release: {{ .Release.Name  }}
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 0
      containers:
      - name: {{ .Values.deployment.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http-port
          containerPort: {{ .Values.service.internalPortHttp }}
        - name: jnlp-port
          containerPort: {{ .Values.service.internalPortJnlp }}
        volumeMounts:
        - name: {{ .Values.volume.name }}
          mountPath: {{ .Values.volume.mountPath | quote }}
      volumes:
      - name: {{ .Values.volume.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.volume.claimName }}
